#python 3
#bin/instance stop; bin/instance run  find_havn_etc.py  -O skipshistorie
#DexterityContent.UID o

#import pandas as pd
#import openpyxl
from zope.lifecycleevent import modified
import plone.api
from zope.component.hooks import setSite
from plone.app.textfield import RichText
from plone.app.textfield.value import RichTextValue
from plone.rfc822.interfaces import IPrimaryFieldInfo
from zope.lifecycleevent import modified
import transaction
from bs4 import BeautifulSoup
import re


setSite(app['skipshistorie'])

brains = app.skipshistorie.portal_catalog(portal_type=["Document", "skip"], sort_on="modified", sort_order='descending')
#brains = app.skipshistorie.portal_catalog(id="lvk20019350300000-pol-vi")

	#import pdb; pdb.set_trace()

findText = [
                            ['klasse', 'Klasse (Class).:'],
							[ 'fangstutstyr',   '  Fangstutstyr: (catching equipm.)'],
                            [   'fangstutstyr', ' (catching equipm.):'],
							[ 'fangstutstyr',   ' Fangstutstyr (Catching equip.)'],
							[ 'fangstutstyr',   'Fangstutstyr:(catching equipm.)'],
							[ 'fangstutstyr',  '   Fangstutstyr. (catching equipm.)'],
							[ 'fangstutstyr',  '  Fabrikkutstyr. (factory equipm.)'],
							[ 'fangstutstyr',  '  Fangstutstyr (catching equipm.)'],
							[ 'fangstutstyr',  '  Fangstutstyr (catching equipm)'],
							[ 'fangstutstyr',  '  Fangstutstyr: (catching equipm.)'],
							[ 'fangstutstyr',  '  Fangstutstyr. (catching equipm.)'],
							[ 'fangstutstyr',  '  Fangstutstyr/equipm.'],
							[ 'fangstutstyr',  ' Fangstutstyr (catching equipm.)'],
							[ 'fangstutstyr',  ' Fangstutstyr: (catching equipm.)'],
							[ 'fangstutstyr',  ' Fangstutstyr: (catching equipm.)'],
							[ 'fangstutstyr',  ' Fangstutstyr. (catching equipm.)'],
							[ 'fangstutstyr',  ' Fangstutstyr. (catching equipment)'],
							[ 'fangstutstyr',  'Fangstutstyr. (catching equipm.)'],
							[ 'fangstutstyr',  'Fangstutstyr.(catching equipm.)'],
							[ 'fangstutstyr',  'Fangstutstyr.(catching equipm.)'],
							['bemanning', '  Bemanning (crew)'],
							['bemanning', '  Bemanning Crew)'],
							['bemanning', '  Bemanning'],
							['bemanning', ' Bemanning  (crew)'],
							['bemanning', ' Bemanning (crew): '],
							['bemanning', ' Bemanning (crew):'],
							['bemanning', ' Bemanning (crew)'],
							['bemanning', ' Bemanning (crew)'],
							['bemanning', 'Bemanning  (crew)'],
							['bemanning', 'Bemanning (crew): '],
							['bemanning', 'Bemanning (crew):'],
							['bemanning', 'Bemanning (crew)'],
							['bemanning', 'Bemanning (crew)'],
							['bemanning', 'Bemanning (crew)'],
							['bnr', '   Bnr (Sno).'],
							['bnr', '  B. nr (Sno).'],
							['bnr', '  Bygg  nr. Sno'],
							['bnr', '  Bygg  nr. Sno'],
							['bnr', '  Bygg  nr.'],
							['bnr', '  Bygg nr. Sno'],
							['bnr', '  Bygg nr.'],
							['bnr', ' B.nr  (Sno).'],
							['bnr', ' B.nr (Sno).'],
							['bnr', ' B.nr. (Sno.)'],
							['bnr', ' B.nr. (Sno)'],
							['bnr', ' Bnr (Sno): '],
							['bnr', ' Bnr (Sno):'],
							['bnr', ' Bnr (Sno).:'],
							['bnr', ' Bnr.  (Sno.)'],
							['bnr', ' Bnr. (Sno.)'],
							['bnr', ' Bnr. (Sno).'],
							['bnr', ' Bnr. (Sno)'],
							['bnr', ' Bnr. Sno'],
							['bnr', ' Bnr'],
							['bnr', ' Bygg nr. Sno'],
							['bnr', ' Bygg nr.'],
							['bnr', 'Bnr  (Sno):'],
							['bnr', 'Bnr  (Sno).:'],
							['bnr', 'Bnr (Sno):'],
							['bnr', 'Bnr (Sno):'],
							['bnr', 'Bnr (Sno).: '],
							['bnr', 'Bnr (Sno).:'],
							['bnr', 'Bnr (Sno).:'],
							['bnr', 'Bnr (Sno).:'],
							['bnr', 'Bnr (Sno).'],
							['bnr', 'Bnr (Sno).'],
							['bnr', 'Bnr (Sno).'],
							['bnr', 'Bnr (Sno)'],
							['bnr', 'Bnr(Sno).: '],
							['bnr', 'Bygg  nr. Sno'],
							['bnr', 'Bygg nr. Sno'],
							['bnr', 'Bygg nr. Sno'],
							['bnr', 'Bygg nr.'],
							['byggeaar', '   Byggeår (year built)'],
							['byggeaar', '  Bygge år/year'],
							['byggeaar', '  Byggeår  (year built)'],
							['byggeaar', '  Byggeår (year   built)'],
							['byggeaar', '  Byggeår (year  built)'],
							['byggeaar', '  Byggeår (year built):\xa0\xa0 '],
							['byggeaar', '  Byggeår (year built)'],
							['byggeaar', '  Bysseutstyr(galley equipment)'],
							['byggeaar', ' Bygge&aring;r (year built):'],
							['byggeaar', ' Byggeår  (year built)'],
							['byggeaar', ' Byggeår (year  built)'],
							['byggeaar', ' Byggeår (year built):'],
							['byggeaar', ' Byggeår (year built)'],
							['byggeaar', 'Byggeår  (year built)'],
							['byggeaar', 'Byggeår (year  built)'],
							['byggeaar', 'Byggeår (year built): '],
							['byggeaar', 'Byggeår (year built):'],
							['byggeaar', 'Byggeår (year built)'],
							['byggeaar', 'Byggeår (year built)'],
							['byggeaar', 'Byggeår (year built)'],
							['dekkmaskineri', '   Dekksmaskineri   (deck machinery)'],
							['dekkmaskineri', '   Dekksmaskineri  (deck machinery)'],
							['dekkmaskineri', '   Dekksmaskineri (deck machinery)'],
							['dekkmaskineri', ' \xa0 Dekksmaskineri (deck machinery)'],
							['dekkmaskineri', ' Dekksmaskineri '],
							['dekkmaskineri', ' Dekksmaskineri (deck machinery)'],
							['dekkmaskineri', ' Dekksmaskineri'],
							['dekkmaskineri', 'Dekksmaskineri '],
							['dekkmaskineri', 'Dekksmaskineri'],
							['dekkmaskineri', 'Dekksmaskineri(deck machinery)'],
							['dekkmaskineri', 'Dekksmaskineri(deck machinery)'],
							['dimensjoner', '   Dimensjoner (size)'],
							['dimensjoner', '  Dimensjoner   (size)'],
							['dimensjoner', '  Dimensjoner  (size)'],
							['dimensjoner', '  Dimensjoner (size)'],
							['dimensjoner', '  Dimensjoner'],
							['dimensjoner', ' Dimensjoner  (size)'],
							['dimensjoner', ' Dimensjoner  (size)'],
							['dimensjoner', ' Dimensjoner (size):'],
							['dimensjoner', 'Dimensjoner (size): '],
							['dimensjoner', 'Dimensjoner (size):'],
							['dimensjoner', 'Dimensjoner (size)'],
							['dimensjoner', 'Dimensjoner (size)'],
							['dimensjoner', 'Dimensjoner (size)'],
							['disponent', '  Disponent  (manager)'],
							['disponent', '  Disponent (manager)'],
							['disponent', ' Disponent  (manager)'],
							['disponent', ' Disponent  (managers)'],
							['disponent', ' Disponent (manager): '],
							['disponent', ' Disponent (manager):'],
							['disponent', ' Disponent(manager)'],
							['disponent', 'Disponent  (manager)'],
							['disponent', 'Disponent (manager):'],
							['disponent', 'Disponent (manager)'],
							['disponent', 'Disponent (manager)'],
							['eier', '   Eier (owner)'],
							['eier', '  Eier (owner)'],
							['eier', ' Eier (owner):'],
							['eier', ' Eier (owner):'],
							['eier', ' Eier (owner)'],
							['eier', 'Eier (owner): '],
							['eier', 'Eier (owner):'],
							['eier', 'Eier (owner):'],
							['eier', 'Eier (owner)'],
							['eier', 'Eier (owner)'],
							['eier', 'Eier (owner)'],
							['eier', 'Eier (owner)'],
							['fart', '   Fart/forbr.(speed/cons.): '],
							['fart', '  Fart/forbr .(speed/cons.): '],
							['fart', '  Fart/forbr. (speed/cons.): '],
							['fart', '  Fart/forbr. (speed/cons.)'],
							['fart', '  Fart/forbr. speed/cons.): '],
							['fart', '  Fart/forbr.speed/cons.): '],
							['fart', '  Fart/forbruk/speed/cons.: '],
							['fart', ' Fart/forbr  .(speed/cons.): '],
							['fart', ' Fart/forbr.  (speed/cons.): '],
							['fart', ' Fart/forbr. (speed/cons.): '],
							['fart', ' Fart/forbr. (speed/cons.): '],
							['fart', ' Fart/forbr. (speed/cons.)'],
							['fart', ' Fart/forbr.(speed/cons.) '],
							['fart', ' Fart/forbr.\xa0 (speed/cons.): '],
							['fart', 'Fart/forbr.  (speed/cons.): '],
							['fart', 'Fart/forbr. (speed/cons.): '],
							['fart', 'Fart/forbr. (speed/cons.): '],
							['fart', 'Fart/forbr. (speed/cons.): '],
							['fart', 'Fart/forbr. (speed/cons.):'],
							['fart', 'Fart/forbr.(speed/cons.): '],
							['flagg',  'Flagg  (flag)'],
							['flagg',  'Flagg (flag)'],
							['flagg',  'Flagg/flag'],
							['flagg', '   Flagg (flag)'],
							['flagg', '  Flagg   (flag)'],
							['flagg', ' Flagg   (flag)'],
							['flagg', ' Flagg  (flag)'],
							['flagg', ' Flagg (flag): '],
							['flagg', ' Flagg (flag)'],
							['flagg', 'Flagg  (flag)'],
							['flagg', 'Flagg (flag)'],
							['flagg', 'Flagg (flag)'],
							['flagg', 'Flagg (flag)'],
							['fremdrift', '   Fremdrift (propulsion)'],
							['fremdrift', '  Fremdrift  (propulsion)'],
							['fremdrift', '  Fremdrift (propulsion)'],
							['fremdrift', '  Fremdrift(propulsion)'],
							['fremdrift', ' Fremdrift  (propulsion)'],
							['fremdrift', ' Fremdrift (propulsion): '],
							['fremdrift', ' Fremdrift (propulsion):'],
							['fremdrift', ' Fremdrift (propulsion)'],
							['fremdrift', ' Fremdrift(propulsion)'],
							['fremdrift', 'Fremdrift  (propulsion)'],
							['fremdrift', 'Fremdrift (propulsion): '],
							['fremdrift', 'Fremdrift (propulsion):'],
							['fremdrift', 'Fremdrift (propulsion)'],
							['fremdrift', 'Fremdrift (propulsion)'],
							['havn', '   Havn (port)'],
							['havn', '   Havn(port)'],
							['havn', '  Havn'],
							['havn', '  Reg. havn'],
							['havn', '  Reg.havn'],
							['havn', ' Havn (port)'],
							['havn', ' Havn(port):'],
							['havn', ' Havn(port)'],
							['havn', ' Reg.havn'],
							['havn', 'Havn  (port):'],
							['havn', 'Havn (port):'],
							['havn', 'Havn (port):'],
							['havn', 'Havn (port)'],
							['havn', 'Havn (port)'],
							['havn', 'Havn (port)'],
							['havn', 'Havn(port): '],
							['havn', 'Havn(port):'],
							['havn', 'Havn(port)'],
							['havn', 'Reg. havn'],
							['havn', 'Reg.havn'],
							['historikk',   '   Historikk'],
							['historikk', '  \xa0Historie'],
							['historikk', '  Historie'],
							['historikk', '  Historikk: '],
							['historikk', '  Historikk'],
							['historikk', ' Historikk:'],
							['historikk', ' Historikk'],
							['historikk', 'Historikk: '],
							['historikk', 'Historikk:'],
							['historikk', 'Historikk'],
							['history', '   History in English'],
							['history', '  \xa0History in English'],
							['history', '  History   in English'],
							['history', '  History  in English'],
							['history', '  History in  English'],
							['history', '  History in english'],
							['history', '  History'],
							['history', ' History  in English'],
							['history', ' History in   English'],
							['history', ' History in  English'],
							['history', ' History in English:'],
							['history', ' History in english'],
							['history', ' History in English'],
							['history', 'History  in English'],
							['history', 'History in  English'],
							['history', 'History in English: '],
							['history', 'History in English:'],
							['history', 'History in english'],
							['history', 'History in English'],
							['hjelpemaskineri', '   Hjelpemaskineri (aux)'],
							['hjelpemaskineri', '  Hjelpemaskineri (aux.)'],
							['hjelpemaskineri', '  Hjelpemaskineri (aux)'],
							['hjelpemaskineri', '  Hjelpemaskineri(aux)'],
							['hjelpemaskineri', '  Hjelpemaskineri/aux.'],
							['hjelpemaskineri', ' Hjelpemaskineri  (aux)'],
							['hjelpemaskineri', ' Hjelpemaskineri (aux): '],
							['hjelpemaskineri', ' Hjelpemaskineri (aux):'],
							['hjelpemaskineri', ' Hjelpemaskineri (aux)'],
							['hjelpemaskineri', 'Hjelpemaskineri  (aux)'],
							['hjelpemaskineri', 'Hjelpemaskineri (aux): '],
							['hjelpemaskineri', 'Hjelpemaskineri (aux):'],
							['hjelpemaskineri', 'Hjelpemaskineri (aux)'],
							['hjelpemaskineri', 'Hjelpemaskineri (aux)'],
							['kallesignal', '   Kallesignal (Call sign.)'],
							['kallesignal', '   Kallesignal (Call sign)'],
							['kallesignal', '   Kilde: oslobyleksikon.no.'],
							['kallesignal', '   Kjenningssignal'],
							['kallesignal', '  Kallesignal (Call sign)'],
							['kallesignal', '  Kallesignal (Callsign)'],
							['kallesignal', '  Kallesignal(Call sign)'],
							['kallesignal', ' Kallesignal  (Call sign.)'],
							['kallesignal', ' Kallesignal  (Call sign.)'],
							['kallesignal', ' Kallesignal  (Call sign)'],
							['kallesignal', ' Kallesignal (Call  sign.)'],
							['kallesignal', ' Kallesignal (Call  sign)'],
							['kallesignal', ' Kallesignal (Call sign.):'],
							['kallesignal', ' Kallesignal (Call sign.)'],
							['kallesignal', ' Kallesignal (Call sign): '],
							['kallesignal', ' Kallesignal (Callsign)'],
							['kallesignal', ' Kallesignal(Call sign)'],
							['kallesignal', 'Kallesignal (Call  sign.)'],
							['kallesignal', 'Kallesignal (Call  sign)'],
							['kallesignal', 'Kallesignal (Call sign.): '],
							['kallesignal', 'Kallesignal (Call sign.):'],
							['kallesignal', 'Kallesignal (Call sign):'],
							['kallesignal', 'Kallesignal (Call sign):'],
							['kallesignal', 'Kallesignal (Call sign)'],
							['kallesignal', 'Kallesignal (Call sign)'],
							['kallesignal',' Kallesignal (Call sign):'],
							['kjeler', '   Kjele(r) (boiler)'],
							['kjeler', '   Kjeler (boiler)'],
							['kjeler', '  Kjele (boiler)'],
							['kjeler', '  Kjele (r) (boiler)'],
							['kjeler', '  Kjele(r)  (boiler)'],
							['kjeler', '  Kjele(r) (boilers)'],
							['kjeler', '  Kjele(r)/boiler'],
							['kjeler', '  Kjele® (boiler)'],
							['kjeler', '  Kjeler  (boiler)'],
							['kjeler', '  Kjeler (boiler)'],
							['kjeler', '  Kjeler (Boilers)'],
							['kjeler', ' Kjele(r)  (boiler)'],
							['kjeler', ' Kjele(r) (boiler): '],
							['kjeler', ' Kjele(r) (boiler):'],
							['kjeler', ' Kjele(r) (boiler)'],
							['kjeler', ' Kjele(r) (boilers)'],
							['kjeler', ' Kjele®  (boiler)'],
							['kjeler', ' Kjele® (boiler)'],
							['kjeler', ' Kjeler  (boilers)'],
							['kjeler', ' Kjeler (boiler): '],
							['kjeler', ' Kjeler (boiler):'],
							['kjeler', ' Kjeler (boilers): '],
							['kjeler', ' Kjeler (boilers):'],
							['kjeler', ' Kjeler (Boilers)'],
							['kjeler', 'Kjele(r)  (boiler)'],
							['kjeler', 'Kjele(r) (boiler): '],
							['kjeler', 'Kjele(r) (boiler):'],
							['kjeler', 'Kjele(r) (boiler)'],
							['kjeler', 'Kjele(r) (boiler)'],
							['kjeler', 'Kjele®  (boiler)'],
							['kjeler', 'Kjele® (boiler)'],
							['kjeler', 'Kjeler  (boiler)'],
							['kjeler', 'Kjeler  (Boilers)'],
							['kjeler', 'Kjeler (boiler): '],
							['kjeler', 'Kjeler (boiler):'],
							['kjeler', 'Kjeler (boiler)'],
							['kjeler', 'Kjeler (boiler)'],
							['kjeler', 'Kjeler (boilers): '],
							['kjeler', 'Kjeler (boilers):'],
							['kjeler', 'Kjeler (Boilers)'],
							['kjolemaskineri', '   Kjølemaskineri: (Refr. machinery)'],
							['kjolemaskineri', '   Kjølemaskineri. (Ref.  machinery.)'],
							['kjolemaskineri', '   Kjølemaskineri. (Ref. machinery.)'],
							['kjolemaskineri', '   Kjølemaskineri. (Ref. machinery)'],
							['kjolemaskineri', '   Kjølemaskineri. (Refr. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri.   (Ref. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri.  (Ref. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri.  (Refr.  machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri.  (Refr. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri. (Ref. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri. (Ref. machinery)'],
							['kjolemaskineri', '  Kjølemaskineri. (Refr. machinery.)'],
							['kjolemaskineri', '  Kjølemaskineri. Refr. machinery.'],
							['kjolemaskineri', ' Kjølemask. (refrig. machinery)'],
							['kjolemaskineri', ' Kjølemaskiner. (Ref. machinery)'],
							['kjolemaskineri', ' Kjølemaskineri '],
							['kjolemaskineri', ' Kjølemaskineri '],
							['kjolemaskineri', ' Kjølemaskineri (Ref. machinery)'],
							['kjolemaskineri', ' Kjølemaskineri: (Ref. maschinery)'],
							['kjolemaskineri', ' Kjølemaskineri: (Refr. machinery)'],
							['kjolemaskineri', ' Kjølemaskineri. (Ref. machinery.)'],
							['kjolemaskineri', ' Kjølemaskineri. (Refr. machinery.)'],
							['kjolemaskineri', ' Kjølemaskineri'],
							['kjolemaskineri', ' Kjølemaskineri'],
							['kjolemaskineri', 'Kjølemaskineri. '],
							['kjolemaskineri', 'Kjølemaskineri. (Ref. machinery.)'],
							['kjolemaskineri', 'Kjølemaskineri. (Refr. machinery.)'],
							['kjolemaskineri', 'Kjølemaskineri.'],
							['kjolemaskineri', 'Kjølemaskineri.'],
							['kjolemaskineri', 'Kjølemaskineri.(Ref. machinery.)'],
							['kjolemaskineri', 'Kjølemaskineri.(Ref. machinery.)'],
							['kjolemaskineri', 'Kjølemaskineri'],
							['kjolemaskineri', 'Kjølemaskineri'],
							['kjolemaskineri', 'Kjølemaskineri'],
							['kjolemaskineri', 'Kjølemaskineri'],
							['klasse', '   Klasse (Class).'],
							['klasse', '  Klasse   (Class).'],
							['klasse', '  Klasse  (Class).'],
							['klasse', '  Klasse (Class).'],
							['klasse', ' Klasse  (Class).'],
							['klasse', ' Klasse  (Class)'],
							['klasse', ' Klasse (Class'],
							['klasse', ' Klasse (Class).: '],
							['klasse', ' Klasse (Class).:'],
							['klasse', ' Klasse (Class).:'],
							['klasse', ' Klasse(Class).: '],
							['klasse', 'Klasse  (Class).'],
							['klasse', 'Klasse  (Class)'],
							['klasse', 'Klasse (Class'],
							['klasse', 'Klasse (Class):'],
							['klasse', 'Klasse (Class).:'],
							['klasse', 'Klasse (Class).:'],
							['klasse', 'Klasse (Class).'],
							['klasse', 'Klasse (Class).'],
							['klasse', 'Klasse (Class).'],
							['klasse', 'Klasse (Class)'],
							['klasse', 'Klasse/Class.'],
                            ['klasse', 'Klasse (Class).:'],
                            ['kommunikasjon', ' Kommunikasjons utstyr (comm.equipm.):'],
							['kommunikasjon', '   Kommunikasjon  (comm.)'],
							['kommunikasjon', '   Kommunikasjons utstyr (comm. equipm.)'],
							['kommunikasjon', '   Kommunikasjons utstyr (comm.equipm.)'],
							['kommunikasjon', '   Kommunikasjonsutstyr  (comm. equipm.)'],
							['kommunikasjon', '   Kommunikasjonsutstyr (comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjon  (comm.)'],
							['kommunikasjon', '  Kommunikasjon (comm. )'],
							['kommunikasjon', '  Kommunikasjon (comm..)'],
							['kommunikasjon', '  Kommunikasjon (comm.) '],
							['kommunikasjon', '  Kommunikasjon (comm.)'],
							['kommunikasjon', '  Kommunikasjon (comm)'],
							['kommunikasjon', '  Kommunikasjon comm.)'],
							['kommunikasjon', '  Kommunikasjon utstyr  (comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjon(comm.): '],
							['kommunikasjon', '  Kommunikasjon(comm.)'],
							['kommunikasjon', '  Kommunikasjon\xa0  (comm.)'],
							['kommunikasjon', '  Kommunikasjon\xa0 (comm.)'],
							['kommunikasjon', '  Kommunikasjon\xa0(comm.)'],
							['kommunikasjon', '  Kommunikasjoncomm)'],
							['kommunikasjon', '  Kommunikasjons (comm.)'],
							['kommunikasjon', '  Kommunikasjons utstyr  (comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjons utstyr  (comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjons utstyr (comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjons utstyr (comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjons utstyr comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr  (comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr  (comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr (comm. equipm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr (comm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr (comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjonsutstyr \xa0(comm.equipm.)'],
							['kommunikasjon', '  Kommunikasjonutstyr  (comm. equipm.)'],
							['kommunikasjon', ' Kommunikasjon  (comm.)'],
							['kommunikasjon', ' Kommunikasjon (comm.): '],
							['kommunikasjon', ' Kommunikasjon (comm.):'],
							['kommunikasjon', ' Kommunikasjon (comm.)'],
							['kommunikasjon', ' Kommunikasjon (comm.)'],
							['kommunikasjon', ' Kommunikasjon comm.)'],
							['kommunikasjon', ' Kommunikasjon'],
							['kommunikasjon', ' Kommunikasjons utstyr (comm.equipm.)'],
							['kommunikasjon', ' Kommunikasjonsutstyr  (comm. equipm.)'],
							['kommunikasjon', ' Kommunikasjonsutstyr (comm. equipm.)'],
							['kommunikasjon', ' Kommunikasjonutstyr \xa0(comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjon  (comm.)'],
							['kommunikasjon', 'Kommunikasjon (comm.): '],
							['kommunikasjon', 'Kommunikasjon (comm.):'],
							['kommunikasjon', 'Kommunikasjon (comm.)'],
							['kommunikasjon', 'Kommunikasjon (comm.)'],
							['kommunikasjon', 'Kommunikasjon(comm.)'],
							['kommunikasjon', 'Kommunikasjons utstyr  (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjons utstyr (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjons utstyr (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr  (comm. equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr  (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr (comm. equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr (comm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr (comm.equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr(comm. equipm.)'],
							['kommunikasjon', 'Kommunikasjonsutstyr(comm. equipm.)'],
							['kommunikasjon', ' (comm. equipm.):'],
							['kommunikasjon', ' Kommunikasjonsutstyr'],
							['lasthandtering', '   Lasthåndtering  (cargo handling.)'],
							['lasthandtering', ' (cargo handling):'],
							['lasthandtering', ' Lasthåndteringsyst.'],
							['lasthandtering', '   Lasthåndtering (cargo handling.)'],
							['lasthandtering', '   Lasthåndtering. (cargo handling.)'],
							['lasthandtering', '   Lasthåndtering. (cargo handling)'],
							['lasthandtering', '   Lasthåndteringsyst.  (cargo handling)'],
							['lasthandtering', '   Lasthåndteringsyst. (cargo handling.)'],
							['lasthandtering', '   Lasthåndteringsyst. (cargo handling)'],
							['lasthandtering', '  Lastehandtering (cargo handling.)'],
							['lasthandtering', '  Lastehandterings syst. (cargo handling.)'],
							['lasthandtering', '  Lastehandterings syst. (cargo handling)'],
							['lasthandtering', '  Lastehandteringssyst. (cargo handling.)'],
							['lasthandtering', '  Lastehandteringsyst. (cargo handling.)'],
							['lasthandtering', '  Lasthandteringssyst. (cargo handling.)'],
							['lasthandtering', '  Lasthandteringsyst. (cargo handling.)'],
							['lasthandtering', '  Lasthandteringsyst. (cargo handling)'],
							['lasthandtering', '  Lasthndteringsyst. (cargo handling.)'],
							['lasthandtering', '  Lasthndteringsyst. (cargo handling)'],
							['lasthandtering', '  Lasthåndterin (cargo handling)'],
							['lasthandtering', '  Lasthåndtering (cargo handling)'],
							['lasthandtering', '  Lasthåndtering syst. (cargo handling.)'],
							['lasthandtering', '  Lasthåndtering. (cargo handling.)'],
							['lasthandtering', '  Lasthåndtering. (cargo handling)'],
							['lasthandtering', '  Lasthåndtering(cargo handling)'],
							['lasthandtering', '  Lasthåndterings syst. (cargo handling.)'],
							['lasthandtering', '  Lasthåndterings syst. (cargo handling)'],
							['lasthandtering', '  Lasthåndteringssyst. (cargo handling)'],
							['lasthandtering', '  Lasthåndteringsyst. (cargo handling.)'],
							['lasthandtering', '  Lasthåndteringsyst. (cargo handling): '],
							['lasthandtering', '  Lasthåndteringsyst. (cargo handling):\xa0\xa0 '],
							['lasthandtering', '  Lasthåndteringsyst. (cargo handling)'],
							['lasthandtering', '  Lasthåndteringyst. (cargo handling)'],
							['lasthandtering', ' (cargo handling.)'],
							['lasthandtering', ' Lastehandtering (cargo handling.)'],
							['lasthandtering', ' Lastehandterings syst. (cargo handling.)'],
							['lasthandtering', ' Lasthåndtering '],
							['lasthandtering', ' Lasthåndtering'],
							['lasthandtering', ' Lasthåndtering'],
							['lasthandtering', ' Lasthåndterings  syst. (cargo handling.)'],
							['lasthandtering', ' Lasthåndteringsyst. (cargo handling.)'],
							['lasthandtering', ' Lasthåndteringsyst. (cargo handling)'],
							['lasthandtering', 'Lastehandtering (cargo handling.)'],
							['lasthandtering', 'Lastehandterings syst. (cargo handling.)'],
							['lasthandtering', 'Lastehandterings syst. (cargo handling.)'],
							['lasthandtering', 'Lastehandterings syst.(cargo handling.)'],
							['lasthandtering', 'Lastehandteringssyst.'],
							['lasthandtering', 'Lasthandteringssyst.(cargo handling.)'],
							['lasthandtering', 'Lasthåndterin (cargo handling.)'],
							['lasthandtering', 'Lasthåndtering '],
							['lasthandtering', 'Lasthåndtering. (cargo handling)'],
							['lasthandtering', 'Lasthåndtering'],
							['lasthandtering', 'Lasthåndtering(cargo handling.)'],
							['lasthandtering', 'Lasthåndteringsyst. '],
							['lasthandtering', 'Lasthåndteringsyst. (cargo handling.)'],
							['lasthandtering', 'Lasthåndteringsyst. (cargo handling)'],
							['lasthandtering', 'Lasthåndteringsyst.(cargo handling.)'],
							['lasthandtering', 'Lasthåndteringsyst.(cargo handling): '],
							['lasthandtering', 'Lasthåndteringsyst.(cargo handling)'],
							['lasthandtering', 'Lasthåndteringsyst.(cargo handling)'],
                            ['lasthandtering', ' (cargo handling.):'],
                            ['manouvering', '   Manøversystemer  (syst. for manouvering)'],
							['manouvering', '  Manøversystemer (syst. for manouvering)'],
							['manouvering', ' Manøversystemer ' ],
							['manouvering', ' Manøversystemer' ],
							['manouvering', 'Manøversystemer ' ],
							['manouvering', 'Manøversystemer ' ],
							['manouvering', 'Manøversystemer' ],
							['manouvering', 'Manøversystemer(syst. for manouvering)'],
							['manouvering', 'Manøversystemer(syst. for manouvering)'],
							['manouvering', 'Manøversystemer(syst.for manouvering)'],
							['navigasjonsutstyr',  ' Navigasjonsutstyr: '],
							['navigasjonsutstyr',  ' Navigasjonsutstyr:'],
							['navigasjonsutstyr',  'Navigasjonsutstyr: '],
							['navigasjonsutstyr',  'Navigasjonsutstyr:'],
							['navigasjonsutstyr', '   Navigasjonsutstyr'],
							['navigasjonsutstyr', '  Navigasjonsutstyr'],
							['navigasjonsutstyr', ' Navigasjonsutstyr'],
							['navigasjonsutstyr', ' Navigasjonsutstyr'],
							['navigasjonsutstyr', 'Navigasjonsutstyr'],
							['navigasjonsutstyr', 'Navigasjonsutstyr'],
							['off_nr', '   ID no'],
                            ['off_nr', 'ID. No.:'],
							['off_nr', '   Id.no'],
							['off_nr', '   Off. no.'],
							['off_nr', '   Off.no  (IMO)'],
							['off_nr', '   Off.no'],
							['off_nr', '  ID '],
							['off_nr', '  ID.   No.'],
							['off_nr', '  ID. '],
							['off_nr', '  ID. No.'],
							['off_nr', '  Id. nr.'],
							['off_nr', '  ID.'],
							['off_nr', '  Id.no: IMO'],
							['off_nr', '  Id.no. IMO'],
							['off_nr', '  Id.no'],
							['off_nr', '  IMO (ID) No.'],
							['off_nr', '  IMO (ID) no'],
							['off_nr', '  IMO no'],
							['off_nr', '  In English'],
							['off_nr', '  Off no'],
							['off_nr', '  Off. no. (IMO)'],
							['off_nr', '  Off. no.'],
							['off_nr', '  Off.no  (IMO)'],
							['off_nr', '  Off.no: 192'],
							['off_nr', '  Off.no: 242'],
							['off_nr', '  Off.no: 705'],
							['off_nr', '  Off.no.'],
							['off_nr', '  Off.no'],
							['off_nr', ' ID no'],
							['off_nr', ' ID nr'],
							['off_nr', ' ID:'],
							['off_nr', ' ID.   No.'],
							['off_nr', ' ID.  No.'],
							['off_nr', ' ID. No.'],
							['off_nr', ' Id.no: IMO'],
							['off_nr', ' Id.no'],
							['off_nr', ' Id.no'],
							['off_nr', ' ID'],
							['off_nr', ' IMO (ID) No.'],
							['off_nr', ' IMO (ID). No.'],
							['off_nr', ' IMO no'],
							['off_nr', ' Off no'],
							['off_nr', ' Off.   no.'],
							['off_nr', ' Off.  no.'],
							['off_nr', ' Off.  no'],
							['off_nr', ' Off.  nr.'],
							['off_nr', ' Off. no: '],
							['off_nr', ' Off. no:'],
							['off_nr', ' Off. no:'],
							['off_nr', ' Off. no.: '],
							['off_nr', ' Off. no.'],
							['off_nr', ' Off. nr.:'],
							['off_nr', ' Off. nr.'],
							['off_nr', ' Off.no   (IMO)'],
							['off_nr', ' Off.no  (IMO)'],
							['off_nr', ' Off.no '],
							['off_nr', ' Off.no (IMO):'],
							['off_nr', ' Off.no (IMO)'],
							['off_nr', ' Off.no: '],
							['off_nr', ' Off.no:'],
							['off_nr', ' Off.no.'],
							['off_nr', ' Off.no.(IMO)'],
							['off_nr', 'ID no'],
							['off_nr', 'ID. No.'],
							['off_nr', 'ID. No.'],
							['off_nr', 'Id.no'],
							['off_nr', 'IMO no'],
							['off_nr', 'Off no'],
							['off_nr', 'Off. nr.'],
							['off_nr', 'Off.no  (IMO):'],
							['off_nr', 'Off.no  (IMO)'],
							['off_nr', 'Off.no (IMO):'],
							['off_nr', 'Off.no (IMO)'],
							['off_nr', 'Off.no (IMO)'],
							['off_nr', 'Off.no: '],
							['off_nr', 'Off.no:'],
							['off_nr', 'Off.no.'],
							['off_nr', 'Off.no'],
							['off_nr', 'Off.no'],
							['off_nr', "ID:"],
							['power', '   Tot. el. kraft (el. power)'],
							['power', '   Tot.el.kraft (el.power)'],
							['power', '  Tot. el. kraft (el power)'],
							['power', '  Tot. el. kraft (el.  power)'],
							['power', '  Tot. el. kraft (el.power)'],
							['power', '  Tot. el. kraft(el. power)'],
							['power', '  Tot. el. kraft(el.power)'],
							['power', '  Tot.el.kraft(el.power)'],
							['power', ' Fart/forbr.(speed/cons.): '],
							['power', ' Fart/forbr.(speed/cons.):'],
							['power', ' Tot.  el. kraft (el.power)'],
							['power', ' Tot.  el. kraft(el. power)'],
							['power', ' Tot.  el.kraft (el.power)'],
							['power', ' Tot. el.  kraft (el. power)'],
							['power', ' Tot. el. kraft  (el. power)'],
							['power', ' Tot. el. kraft  (el.power)'],
							['power', ' Tot. el. kraft (el.  power)'],
							['power', ' Tot. el. kraft (el. power): '],
							['power', ' Tot. el. kraft (el. power):'],
							['power', ' Tot. el. kraft(el.  power)'],
							['power', ' Tot. el. kraft(el. power)'],
							['power', ' Tot.el.kraft  (el.power)'],
							['power', ' Tot.el.kraft (el. power)'],
							['power', ' Tot.el.kraft (el.power):'],
							['power', ' Tot.el.kraft (el.power)'],
							['power', ' Total el.kraft/el.power'],
							['power', 'Fart/forbr.(speed/cons.): '],
							['power', 'Fart/forbr.(speed/cons.):'],
							['power', 'Tot.  el. kraft (el .power)'],
							['power', 'Tot.  el. kraft (el. power):'],
							['power', 'Tot.  el. kraft (el. power)'],
							['power', 'Tot. el. kraft (el  power)'],
							['power', 'Tot. el. kraft (el.  power)'],
							['power', 'Tot. el. kraft (el. power): '],
							['power', 'Tot. el. kraft (el. power):'],
							['power', 'Tot. el. kraft (el. power):'],
							['power', 'Tot. el. kraft (el. power):'],
							['power', 'Tot. el. kraft (el. power)'],
							['power', 'Tot. el. kraft (el. power)'],
							['power', 'Tot. el. kraft (el.power):'],
							['power', 'Tot. el. kraft (el.power)'],
							['power', 'Tot. el. kraft(el. power)'],
							['power', 'Tot.el.kraft  (el.power)'],
							['power', 'Tot.el.kraft (el.power): '],
							['power', 'Tot.el.kraft (el.power)'],
							['power', 'Tot.el.kraft (el.power)'],
							['shipyard',  'Bygger  (yard)'],
							['shipyard', '   Bygger (yard)'],
							['shipyard', '  Bygger (yard)'],
							['shipyard', '  Bygger/yard'],
							['shipyard', ' Bygger  (yard)'],
							['shipyard', ' Bygger (yard):'],
							['shipyard', 'Bygger (yard): '],
							['shipyard', 'Bygger (yard):'],
							['shipyard', 'Bygger (yard)'],
							['shipyard', 'Bygger (yard)'],
							['shipyard', 'Bygger (yard)'],
							['skipstype', '   Type'],
							['skipstype', '  Type'],
							['skipstype', ' Type:'],
							['skipstype', ' Type'],
							['skipstype', 'Type: '],
							['skipstype', 'Type:'],
							['skipstype', 'Type'],
							['skipstype', 'Type'],
							['tonnasje', '   Tonnasje  (Tonnage)'],
							['tonnasje', '   Tonnasje (Tonnage)'],
							['tonnasje', '  Tonnasje  (Tonnage)'],
							['tonnasje', '  Tonnasje (Tonnage)'],
							['tonnasje', '  Tonnasje/Tonnage'],
							['tonnasje', ' (Tonnage)'],
							['tonnasje', ' \xa0Tonnasje  (Tonnage)'],
							['tonnasje', ' Tonnasje  (Tonnage)'],
							['tonnasje', ' Tonnasje  (Tonnage)'],
							['tonnasje', ' Tonnasje (Tonnage) '],
							['tonnasje', ' Tonnasje (Tonnage):'],
							['tonnasje', ' Tonnasje (Tonnage):'],
							['tonnasje', ' Tonnasje (Tonnage)'],
							['tonnasje', ' Tonnasje (Tonnage)'],
							['tonnasje', ' Tonnasje (Tonnage)'],
							['tonnasje', ' Tonnasje(Tonnage)'],
							['tonnasje', ' Tonnasje(Tonnage)'],
							['tonnasje', 'Tonnasje (Tonnage) '],
							['tonnasje', 'Tonnasje (Tonnage): '],
							['tonnasje', 'Tonnasje (Tonnage):'],
							['tonnasje', 'Tonnasje (Tonnage)'],
							['tonnasje', 'Tonnasje (Tonnage)'],
							['tonnasje', 'Tonnasje (Tonnage)'],
						    ['eier', 'Eier  (owner):'],
						    ['skipstype', 'Type'],
		                    ['flagg', 'Flagg (flag):'],
		                    ['havn', 'Havn (port):'],
	                        ['flagg', ' Flagg (flag):'],
  		                    ['havn', ' Havn (port):'],


						]

if brains:
	print('Total  objects: ')
	print(len(brains))
	ant = 0
	count = 0

	for brain in brains:
			count += 1

			obj = brain.getObject()
			if count % 100 == 1:
				print(count)
				print(obj.Title())

			#print(obj.Title)
			try:
				if '- ' in obj.Title():
					print('12k34')
					abd = 1234
					#import pdb; pdb.set_trace()
			except TypeError:
				#import pdb; pdb.set_trace()
				obj.Title = obj.Title()

			if hasattr(obj, 'havn'):
				if obj.havn and obj.portal_type=="Documemt":
					print('changed one')
					obj.portal_tupe = "skip"

			#print(obj.absolute_url().replace("http://nohost/skipshistorie/", "http://skipshistorie.lokalhistorie.org/"))
			primary_field = IPrimaryFieldInfo(obj)
			if isinstance(primary_field.field, RichText):
					if obj.text:
						oldtext = obj.text.output
						oldtext = oldtext.replace(' lang="NO-BOK"', "")
						oldtext = oldtext.replace(' lang="EN-US"', "")
						oldtext = oldtext.replace("</span><span>", "").replace("  ", " ").replace("  ", " ")
						soup = BeautifulSoup(oldtext, 'html.parser')

						#indField = soup.find(text=entry[1])
						changed = 0

						

						#import pdb; pdb.set_trace()

						for entry in findText:
							#import pdb; pdb.set_trace()
							#print(entry)
							findField = soup.find(text=entry[1])

							if findField:
								#print('found')
								#print(entry[0])
								#import pdb; pdb.set_trace()
								#print('setting field')
								#print(entry[0])
								the_td = findField.find_parent('td')
								the_td['class'] = 'scraped'
								the_td = findField.find_parent('td').find_next('td')
								the_td['class'] = 'scraped'

								#if getattr(obj, entry[0]):
								#import pdb; pdb.set_trace()
								if len(str(getattr(obj, entry[0])))<=5:
											#try:
											value = findField.find_parent('td').find_next('td').text
											value = value.strip().replace("  ", " ")
											if len(str(value)) >= 2:
												print('value set')
												changed = 1
												setattr(obj, entry[0], value)
												#print(obj.absolute_url().replace("http://nohost/skipshistorie/", "http://skipshistorie.lokalhistorie.org/"))


											#except AttributeError:
											#abv = "123"
											#import pdb; pdb.set_trace()
											#print(obj.Title())
											#except ValueError:
											#abv = "123"
											#import pdb; pdb.set_trace()
											#	print(obj.Title())


									#Do nothing

						if obj.portal_type == 'skip':
							hist_type= type(obj.historikk)

							if  str(hist_type) == "<class 'str'>":
								obj.historikk = RichTextValue(obj.historikk)
								changed = 1

							hist_type= type(obj.history)
							if  str(hist_type) == "<class 'str'>":
								obj.history = RichTextValue(obj.history)
								changed = 1

						if changed == 1:
							obj.text = RichTextValue(str(soup))
							#obj.setTitle(obj.Title().title())
							ant = ant + 1
							modified(obj)
							if ant % 100 == 1:
								print('transaction')
								transaction.commit()



	print(ant)
	transaction.commit()
